### ISSUE TITLE
Add global environment variables in dickfile

### ISSUE THREAD

**Issue by mariuszluciow** [dick-the-deployer/dick#107]
Something like that:

``` yml
pipeline: 

jobs:

environmentVariables:
  - key: foo
    value: bar
```
