### ISSUE TITLE
Allow using templates

### ISSUE THREAD

**Issue by mariuszluciow** [dick-the-deployer/dick#155]
Could work like that:

``` yml
envVariables:
  - foo=bar

template:
  url: https://github.com/dick-the-deployer/my-template.git
  ref: master
```
