### ISSUE TITLE
Create repository with example configurations to work with

### ISSUE THREAD

**Issue by mariuszluciow** [dick-the-deployer/dick#41]
Success manual scenario

``` yml
pipeline:
  stages:
  - name: first
    autorun: true
  - name: second
    autorun: true
  - name: third
    autorun: false

jobs: 
  - stage: first
    name: echo foo
    deploy:
      - echo foo
  - stage: second
    name: echo bar
    deploy:
      - echo bar
  - stage: third
    name: echo foobar
    deploy:
      - echo foobar
```

Long build

``` yml
pipeline:
  stages:
  - name: first
    autorun: true
  - name: second
    autorun: true

jobs: 
  - stage: first
    name: echo foo
    deploy:
      - sleep 1000
      - echo foo
  - stage: second
    name: echo bar
    deploy:
      - echo end
```

Failure

``` yml
pipeline:
  stages:
  - name: first
    autorun: true
  - name: second
    autorun: true

jobs: 
  - stage: first
    name: echo foo
    deploy:
      - echo foo
  - stage: second
    name: echo bar
    deploy:
      - exit 1
```
